[package]
name = "xsd-types"
version = "0.1.0"
authors = ["Chris Bruce <chris@lumeo.com>", "leonid.krutovsky <leonid.krutovsky@quantumsoft.ru>", "DmitrySamoylov <dmitry.samoylov@quantumsoft.ru>", "victor-soloviev <victor.soloviev@quantumsoft.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.8"
xml-rs = "0.8.0"
yaserde = "0.3.12"
yaserde_derive = "0.3.12"
chrono = "0.4.10"
itertools = "0.8.1"
num-bigint = "0.2.6"
bigdecimal = "0.1.0"
